// let info = [
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "L",
//     price: "17500",
//     user_id: "",
//     typeName: "Tabla de Stand Up Paddle",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1OO2pGl1X_MNUW-3OUgFP_F05nezYw7PF",
//       "https://drive.google.com/uc?export=view&id=1wf3eYgBb9HIemACfas0KW0UuaT3LWWzR",
//     ],
//     name: "Tabla de Stand Up Paddle Vesl-3569",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "S",
//     price: "12000",
//     user_id: "",
//     typeName: "Tabla de Stand Up Paddle",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1gCEYF3sLYTlsyVRNETV-jZVZSo5o6FjO",
//       "https://drive.google.com/uc?export=view&id=1CHAh8w7APtKLPLfZAmaYlrqWu-lkbB3o",
//     ],
//     name: "Tabla de Stand Up Paddle Vesl-2507",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "L",
//     price: "25500",
//     user_id: "",
//     typeName: "Tabla de Stand Up Paddle",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1HaS_6PwR5gUNtxE3dKcLvAMYoOBTCfC7",
//       "https://drive.google.com/uc?export=view&id=1Bi4DuJeSMk9mJpEqR2ODiSlegvVvPki-",
//     ],
//     name: "Tabla de Stand Up Paddle Vesl-1559",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "XL",
//     price: "10500",
//     user_id: "",
//     typeName: "Tabla de Stand Up Paddle",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1RjJ-IE2qu4HF1sCTR51D-MqbFyVSUD0Y",
//       "https://drive.google.com/uc?export=view&id=1X9JJnLxHFmftppK1ePVLeiTmNL7l2N11",
//     ],
//     name: "Tabla de Stand Up Paddle Vesl-Hunter",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "XXL",
//     price: "20000",
//     user_id: "",
//     typeName: "Tabla de Surf",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1hJQ4k-LBbZioi44U9NIlW3ligG4unXQn",
//       "https://drive.google.com/uc?export=view&id=1PGWFNA6Q0ObeY9syTjJBO-XBmJrcsqEI",
//     ],
//     name: "Tabla de Surf Russell-Hunter v1",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "L",
//     price: "22000",
//     user_id: "",
//     typeName: "Tabla de Surf",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1ZNRz6UF5z-XsFPOYbRh1OqPJWMp2_fMm",
//       "https://drive.google.com/uc?export=view&id=1OyJGXFu4dDrs7mGbSXZg3wNpMu05oJBH",
//     ],
//     name: "Tabla de Surf Russell-Hunter-Hunter v2",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "M",
//     price: "17000",
//     user_id: "",
//     typeName: "Tabla de Surf",
//     imagen: [
//       "https://drive.google.com/file/d/12_h66LIQWEqFU0HZmZa0-sSn3mgI6GdH/view?usp=sharing",
//       "https://drive.google.com/uc?export=view&id=1WEXFCVrGJKpYDSBXGtjpZ-GD61pvyPW7",
//     ],
//     name: "Tabla de Surf Hurley-Geometry v1",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "L",
//     price: "17000",
//     typeName: "Tabla de Surf",
//     user_id: "",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=12wrt54uYLQ_vOxQhxZWzfrQdoMJ1yz8c",
//       "https://drive.google.com/uc?export=view&id=1tHi2v71sSFV7x1yXJ909pcReVdwYt2CN",
//     ],
//     name: "Tabla de Surf Hurley-Geometry v2",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "M",
//     price: "16750",
//     user_id: "",
//     typeName: "Tabla de Surf",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1fHY-EczdiAHEr-knSCdB8jV7mfizEAAh",
//       "https://drive.google.com/uc?export=view&id=1fi1qK8I9uxzIu8UgaXG8sogL6JOiwIbo",
//     ],
//     name: "Tabla de Surf Hurley-Geometry v3",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "S",
//     price: "23750",
//     user_id: "",
//     typeName: "Tabla de Surf",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1_pK_idOC5dnJmYB7d_e3a51FXjA8EkYk",
//       "https://drive.google.com/uc?export=view&id=1GOUBA3vGZDkijb5B1JqhqV-CAT91fRdz",
//     ],
//     name: "Tabla de Surf Wave-Freestyle v4",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "S",
//     price: "13750",
//     user_id: "",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1vuEPfCZNQ_HJAbe_TI-QXUzblxZkqMFI",
//       "https://drive.google.com/uc?export=view&id=1T-dVr732vThiar2D2BMLjigPQ3TEHsnK",
//     ],
//     name: "Tabla de Surf Wave-Freestyle v1",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "M",
//     price: "33750",
//     user_id: "",
//     typeName: "Tabla de Surf",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1MoWRJffpRQdRxHRmcdTPTY7FLU8ejxry",
//       "https://drive.google.com/uc?export=view&id=1bVe_tjROntVPYDvwTayj-LcMuGw95ZP6",
//     ],
//     name: "Tabla de Surf JOBE",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "L",
//     price: "39050",
//     user_id: "",
//     typeName: "Tabla de Surf",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=18GsLcKo54xN90uJgM_KBzJjv0LZ3Q9R0",
//       "https://drive.google.com/uc?export=view&id=1tdllR8xAwAxOhv2e-wbfUnpcAQuix4XM",
//     ],
//     name: "Tabla de Surf JOBE-Explorer",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "XXL",
//     price: "11750",
//     user_id: "",
//     typeName: "Tabla de Surf",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=119Tm0fAtB1-aZTI_UKmmHbM7Sf5BcG6z",
//       "https://drive.google.com/uc?export=view&id=1lAODIfQKMH3Bt6pcqAxiNOeALaZ1ltd0",
//     ],
//     name: "Tabla de Surf Compact-a",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "S",
//     price: "9750",
//     user_id: "",
//     typeName: "Tabla de WakeBoard",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1n5jLCAjcuSpxUfIeJF1GnAzj3qF9emrd",
//       "https://drive.google.com/uc?export=view&id=1dqlDvP-ddYBu2t6lPBKD_xhoadg01nRW",
//     ],
//     name: "Tabla de WakeBoard SungShot-Blue",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "XL",
//     price: "8000",
//     user_id: "",
//     typeName: "Traje De Neopreno",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=145ZwjuCL1l0V-ufwHSqyeFv9X0twRGPB",
//     ],
//     name: "Traje De Neopreno Billabong Mujer Launch 5/4mm Back Zip Gbs - Gris",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "M",
//     price: "11000",
//     user_id: "",
//     typeName: "Traje De Neopreno",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1w0uysUk9S9C-q8VoD1hUnbwtYKxMZ-5K",
//     ],
//     name: " Traje De Neopreno TYPHOON Tormenta Hombre 5/4mm Back Zip - Negro",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "XL",
//     price: "16400",
//     user_id: "",
//     typeName: "Traje De Neopreno",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1mvngpRu-wzsBiIzZ7aYgTNNmxjn-k4xL",
//     ],
//     name: "Traje De Neopreno Gill Zenlite 2mm Flatlock Skiff Hombre - Azul",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "S",
//     price: "13000",
//     user_id: "",
//     typeName: "Traje De Neopreno",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1gCQCAXgYQfacwKLT4bA6e3nFw13YPN6N",
//     ],
//     name: "Femenino Orca Synergy 4/3mm Back Zip Traje - Azul Salvaje",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "XXL",
//     price: "11150",
//     user_id: "",
//     typeName: "Traje De Neopreno",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1pE4A_hwCqBp_QOvoBi_FVATtKc0FKJVH",
//     ],
//     name: "O'neill Traje De Neopreno De Manga Corta Con Chest Zip Para Hombre Hammer 2mm - Pizarra / Negro",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "M",
//     price: "10000",
//     user_id: "",
//     typeName: "Traje De Neopreno",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=15qQvoXiriPPlzF22KwCd2Oo0bHe88IpV",
//     ],
//     name: "O'neill Hombres Atlanta 2mm Back Zip Traje De Neopreno - Negro-Azul",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "S",
//     price: "7500",
//     user_id: "",
//     typeName: "Aletas de buceo",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1xvLbcxMLjuOSPxIW3WTHULlV03Kucawq",
//     ],
//     name: "Powerjet - Aletas de buceo - Powerjet ",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "XL",
//     price: "6500",
//     user_id: "",
//     typeName: "Aletas de buceo",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1UM8jB9uGXVG5kU_6_I-U1DANXliD5yrf",
//     ],
//     name: "Aletas Buceo Mundial One 50 Fin",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "L",
//     price: "6500",
//     user_id: "",
//     typeName: "Aletas de buceo",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1u47YhVDOWHEEGcJiZqsXy5kG69_K9Ib4",
//     ],
//     name: "Aletas de Buceo apnea Mundial One",
//   },
//   {
//     products_id: "",
//     brands_id: "",
//     type_id: "",
//     size: "M",
//     price: "9000",
//     user_id: "",
//     typeName: "Aletas de buceo",
//     imagen: [
//       "https://drive.google.com/uc?export=view&id=1OrCg9TwEumt9DWr1cuHGY1uZLWjbkNWW",
//     ],
//     name: "Powerjet - Aletas de buceo - Bare",
//   },
// ];



// module.exports = {info};
